#!/bin/bash

if [ $# -ne 2 ]; then
  echo "Usage: $0 <namespace> <resource_type>"
  echo "Example: $0 kube-system pods"
  exit 1
fi

NAMESPACE=$1
RESOURCE_TYPE=$2

kubectl top $RESOURCE_TYPE -n $NAMESPACE --no-headers | while read line
do
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  echo "Resource, Namespace, Name, CPU, Memory"
  echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
done
